package form;

import control.*;
import javax.swing.table.DefaultTableModel;


public class frmAdmin extends javax.swing.JInternalFrame {
    MenuUtama mUtama;
    ctrlManipulasiData ctrlManData;
    ctrlAlert ctrlAlert;    
    ctrlComponent ctrlComp;    
    ctrlValidasi ctrlValid;
    

    public frmAdmin(MenuUtama mUtama) {
        initComponents();
        this.mUtama = mUtama;
        ctrlManData = new ctrlManipulasiData(mUtama);
        ctrlAlert = new ctrlAlert(mUtama);        
        ctrlComp = new ctrlComponent();
        ctrlValid = new ctrlValidasi(mUtama);
        
        tblModAdmin = (DefaultTableModel) ctrlComp.getDefaultTabelModel(new String[]{
           "ID Administrator ", "Username", "Nama Administrator", "Password", "Alamat","Nomer HP"
        });
        tblAdmin.setModel(tblModAdmin);
        ctrlComp.setTabel(tblAdmin, new int[]{100,125,200,100,130,200});
        
        txtIdAdmin.setDocument(new control.ctrlTextDoc(15));
        txtUser.setDocument(new control.ctrlTextDoc(30));
        txtNamaAdmin.setDocument(new control.ctrlTextDoc(30));
        txtPass.setDocument(new control.ctrlTextDoc(30));
        txtAlamat.setDocument(new control.ctrlTextDoc(125)); 
        txtNoHp.setDocument(new control.ctrlTextDoc(15, control.ctrlTextDoc.DESIMAL));
        
        
        setAwalForm();
        isiComboCari();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtNamaAdmin = new javax.swing.JTextField();
        lblNamaAdmin = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lblAlamat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        lblIdAdmin = new javax.swing.JLabel();
        txtIdAdmin = new javax.swing.JTextField();
        lblNoHp = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdmin = new javax.swing.JTable();
        lblCari = new javax.swing.JLabel();
        cbCari = new javax.swing.JComboBox();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setClosable(true);
        setTitle("::FORM MASTER ADMINISTRATOR ::"); // NOI18N
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Isi Data Dengan Lengkap"));
        jPanel4.setLayout(null);

        jPanel1.setLayout(null);

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("Username :"); // NOI18N
        jPanel1.add(lblUser);
        lblUser.setBounds(20, 50, 130, 25);

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtUser);
        txtUser.setBounds(160, 50, 140, 25);

        txtNamaAdmin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtNamaAdmin);
        txtNamaAdmin.setBounds(160, 90, 250, 25);

        lblNamaAdmin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNamaAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNamaAdmin.setText("Nama Administrator :"); // NOI18N
        jPanel1.add(lblNamaAdmin);
        lblNamaAdmin.setBounds(20, 90, 130, 25);

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPass.setText("Password :"); // NOI18N
        jPanel1.add(lblPass);
        lblPass.setBounds(10, 130, 140, 25);
        jPanel1.add(txtPass);
        txtPass.setBounds(160, 130, 210, 25);

        lblAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAlamat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAlamat.setText("Alamat :"); // NOI18N
        jPanel1.add(lblAlamat);
        lblAlamat.setBounds(10, 180, 140, 50);

        txtAlamat.setColumns(20);
        txtAlamat.setLineWrap(true);
        txtAlamat.setRows(3);
        txtAlamat.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(160, 170, 250, 70);

        lblIdAdmin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIdAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdAdmin.setText("ID Administrator :"); // NOI18N
        jPanel1.add(lblIdAdmin);
        lblIdAdmin.setBounds(20, 10, 130, 25);

        txtIdAdmin.setEditable(false);
        txtIdAdmin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtIdAdmin);
        txtIdAdmin.setBounds(160, 10, 100, 25);

        lblNoHp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNoHp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNoHp.setText("Nomer HP :"); // NOI18N
        jPanel1.add(lblNoHp);
        lblNoHp.setBounds(10, 260, 140, 25);

        txtNoHp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtNoHp);
        txtNoHp.setBounds(160, 260, 170, 25);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(10, 20, 460, 300);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(20, 0, 480, 340);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save.png"))); // NOI18N
        btnSimpan.setIconTextGap(10);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan);
        btnSimpan.setBounds(40, 350, 80, 40);

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        btnUbah.setIconTextGap(10);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel3.add(btnUbah);
        btnUbah.setBounds(130, 350, 80, 40);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnHapus);
        btnHapus.setBounds(220, 350, 80, 40);

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        btnBatal.setIconTextGap(10);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel3.add(btnBatal);
        btnBatal.setBounds(310, 350, 80, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(400, 350, 80, 40);

        tabPane.addTab("Form Input Data Admin", jPanel3);

        jPanel5.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(null);

        tblAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAdmin);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 480, 340);

        lblCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCari.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCari.setText("Cari Berdasarkan :"); // NOI18N
        jPanel2.add(lblCari);
        lblCari.setBounds(-10, 360, 120, 20);

        cbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCariActionPerformed(evt);
            }
        });
        jPanel2.add(cbCari);
        cbCari.setBounds(110, 360, 80, 20);
        jPanel2.add(txtCari);
        txtCari.setBounds(190, 360, 130, 20);

        btnCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCari.setText("Cari"); // NOI18N
        btnCari.setIconTextGap(10);
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel2.add(btnCari);
        btnCari.setBounds(320, 360, 70, 20);

        jPanel5.add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 390);

        tabPane.addTab("Data Admin", jPanel5);

        getContentPane().add(tabPane);
        tabPane.setBounds(10, 10, 520, 430);

        setBounds(0, 0, 561, 488);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        isiTableAdmin();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        setAwalForm();
    }//GEN-LAST:event_btnBatalActionPerformed
private void setAwalForm() {
        txtIdAdmin.setText(""+new ctrlIDgenerator().getIDAdmin());
        txtUser.setText("");
        txtNamaAdmin.setText("");
        txtPass.setText("");
        txtAlamat.setText("");
        txtNoHp.setText("");
        
        
        btnSimpan.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        
        isiTableAdmin();
    }
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        dapatData();
        
        dataAdmin = new Object []{idAdmin, user, nama, pass, noHp, alamat};
        
        if(ctrlComp.cekIsiField(dataAdmin)){
                       
                if(ctrlAlert.KONFIRMASI(idAdmin, "HAPUS")){
                    String SQL = "DELETE FROM admin WHERE id_admin ='"+idAdmin+"';";
                    if(ctrlManData.EXECUTE_QUERY(SQL,idAdmin,"HAPUS", true)){
                        setAwalForm();
                    }else{
                        setAwalForm();
                    }
                }    
            
        }else{
            ctrlAlert.getDataKosongMessage();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        dapatData();
        
        dataAdmin = new Object []{ idAdmin, user, nama, pass, noHp, alamat};
        
        if(ctrlComp.cekIsiField(dataAdmin)){
       
                if(ctrlAlert.KONFIRMASI(idAdmin, "UBAH")){
                    String SQL = "UPDATE admin SET username='"+user+"', nm_admin='"+nama+"', password='"+pass+"', " +
                                 "alamat='"+alamat+"', no_hp='"+noHp+"' WHERE id_admin='"+idAdmin+"';";
                    if(ctrlManData.EXECUTE_QUERY(SQL,idAdmin,"UBAH", true)){
                        setAwalForm();
                    }else{
                        setAwalForm();
                    }
                }    
            
        }else{
            ctrlAlert.getDataKosongMessage();
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        dapatData();
        
        dataAdmin = new Object []{ idAdmin, nama, pass, alamat, noHp};
        
        if(ctrlComp.cekIsiField(dataAdmin)){
            
                if(ctrlAlert.KONFIRMASI(idAdmin, "SIMPAN")){
                    String SQL = "INSERT INTO admin VALUES('"+idAdmin+"','"+user+"','"+nama+"','"+pass+"','"+alamat+"','"+noHp+"');";
                    if(ctrlManData.EXECUTE_QUERY(SQL,idAdmin,"SIMPAN", true)){
                        setAwalForm();
                    }else{
                        setAwalForm();
                    }
                }    
            
        }else{
            ctrlAlert.getDataKosongMessage();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
     
    int row = 0;
    private void tblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminMouseClicked
        row = tblAdmin.getSelectedRow();
        if(evt.getClickCount()==2){
            txtIdAdmin.setText(tblAdmin.getValueAt(row,0).toString());
            txtUser.setText(tblAdmin.getValueAt(row,1).toString());
            txtNamaAdmin.setText(tblAdmin.getValueAt(row,2).toString());           
            txtPass.setText(tblAdmin.getValueAt(row,3).toString());
                if(ctrlValid.cekAdmin(tblAdmin.getValueAt(row,3).toString())){
                    txtPass.setText(ctrlValid.getPasswordAdmin());
                        }            
            txtAlamat.setText(tblAdmin.getValueAt(row,4).toString());
            txtNoHp.setText(tblAdmin.getValueAt(row,5).toString());
                       
            btnSimpan.setEnabled(false);
            btnUbah.setEnabled(true);
            btnHapus.setEnabled(true);
            
            tabPane.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tblAdminMouseClicked

    private void cbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCariActionPerformed
    
    
    private void isiTableAdmin() {  
        dapatData();
        ctrlComp.removeTable(tblAdmin,tblModAdmin);
        String SQL = "SELECT id_admin, username, nm_admin, '************', alamat, no_hp " +
                     "FROM admin WHERE "+cariBy+" LIKE '%"+kriteria+"%';";
        ctrlManData.setDefaultTable(SQL,tblModAdmin,6);
    }

    private void isiComboCari(){
        cbCari.addItem("ID Administrator");
        cbCari.addItem("Username");
        cbCari.addItem("Nama Administrator");        
        cbCari.addItem("Alamat");
        cbCari.addItem("Nomer HP");
        
    }
    
    private void dapatData(){
         switch(cbCari.getSelectedIndex()){
            case 0 : cariBy = "id_admin"; break;
            case 1 : cariBy = "username"; break;    
            case 2 : cariBy = "nm_admin"; break;
            case 3 : cariBy = "password"; break;
            case 4 : cariBy = "alamat"; break;
            case 5 : cariBy = "nohp"; break;
            default : cariBy = "id_admin";
        }
        kriteria = txtCari.getText().trim();
        
        idAdmin=txtIdAdmin.getText().trim();
        user=txtUser.getText().trim().replaceAll("'","''"); 
        nama=txtNamaAdmin.getText().trim().replaceAll("'","''");         
        pass=String.valueOf(txtPass.getPassword()).replaceAll("'","''");         
        alamat = txtAlamat.getText().trim();
        noHp = ctrlComp.setNoHP(txtNoHp.getText().trim());
        
        
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox cbCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblIdAdmin;
    private javax.swing.JLabel lblNamaAdmin;
    private javax.swing.JLabel lblNoHp;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tblAdmin;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdAdmin;
    private javax.swing.JTextField txtNamaAdmin;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
    private String idAdmin="", user="", nama="", pass="", noHp="", alamat="";    
    public javax.swing.table.DefaultTableModel tblModAdmin;    
    private String cariBy="", kriteria="";
    private Object dataAdmin[];
}
