package form;

import control.*;
import javax.swing.table.DefaultTableModel;


public class frmBarang extends javax.swing.JInternalFrame {
    MenuUtama mUtama;
    ctrlManipulasiData ctrlManData;
    ctrlAlert ctrlAlert;    
    ctrlComponent ctrlComp;    
    ctrlValidasi ctrlValid;
    

    public frmBarang(MenuUtama mUtama) {
        initComponents();
        this.mUtama = mUtama;
        ctrlManData = new ctrlManipulasiData(mUtama);
        ctrlAlert = new ctrlAlert(mUtama);        
        ctrlComp = new ctrlComponent();
        ctrlValid = new ctrlValidasi(mUtama);
        
        tblModBarang = (DefaultTableModel) ctrlComp.getDefaultTabelModel(new String[]{
           "ID Barang ", "Nama Barang", "Quantity"
        });
        tblBarang.setModel(tblModBarang);
        ctrlComp.setTabel(tblBarang, new int[]{100,125,200,100,130,200});
        
        txtIdBarang.setDocument(new control.ctrlTextDoc(5));
        txtNmBarang.setDocument(new control.ctrlTextDoc(30));
        txtQty.setDocument(new control.ctrlTextDoc(11, control.ctrlTextDoc.DESIMAL));
        
        
        setAwalForm();
        isiComboCari();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblNmBarang = new javax.swing.JLabel();
        txtNmBarang = new javax.swing.JTextField();
        lblIdBarang = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        lblQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        lblCari = new javax.swing.JLabel();
        cbCari = new javax.swing.JComboBox();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("::FORM MASTER BARANG ::"); // NOI18N
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Isi Data Dengan Lengkap"));
        jPanel4.setLayout(null);

        jPanel1.setLayout(null);

        lblNmBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNmBarang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNmBarang.setText("Nama Barang :"); // NOI18N
        jPanel1.add(lblNmBarang);
        lblNmBarang.setBounds(0, 60, 100, 25);

        txtNmBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtNmBarang);
        txtNmBarang.setBounds(110, 60, 160, 25);

        lblIdBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIdBarang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdBarang.setText("ID Barang :"); // NOI18N
        jPanel1.add(lblIdBarang);
        lblIdBarang.setBounds(10, 10, 90, 25);

        txtIdBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtIdBarang);
        txtIdBarang.setBounds(110, 10, 120, 25);

        lblQty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQty.setText("Quantity :"); // NOI18N
        jPanel1.add(lblQty);
        lblQty.setBounds(10, 110, 90, 25);

        txtQty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtQty);
        txtQty.setBounds(110, 110, 100, 25);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(10, 20, 420, 150);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(20, 0, 450, 180);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save.png"))); // NOI18N
        btnSimpan.setIconTextGap(10);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan);
        btnSimpan.setBounds(40, 190, 70, 40);

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        btnUbah.setIconTextGap(10);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel3.add(btnUbah);
        btnUbah.setBounds(120, 190, 70, 40);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnHapus);
        btnHapus.setBounds(200, 190, 70, 40);

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        btnBatal.setIconTextGap(10);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel3.add(btnBatal);
        btnBatal.setBounds(280, 190, 70, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(360, 190, 70, 40);

        tabPane.addTab("Form Input Data Barang", jPanel3);

        jPanel5.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(null);

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 480, 170);

        lblCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCari.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCari.setText("Cari Berdasarkan :"); // NOI18N
        jPanel2.add(lblCari);
        lblCari.setBounds(10, 190, 120, 20);

        cbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCariActionPerformed(evt);
            }
        });
        jPanel2.add(cbCari);
        cbCari.setBounds(130, 190, 80, 20);
        jPanel2.add(txtCari);
        txtCari.setBounds(210, 190, 130, 20);

        btnCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCari.setText("Cari"); // NOI18N
        btnCari.setIconTextGap(10);
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel2.add(btnCari);
        btnCari.setBounds(340, 190, 70, 20);

        jPanel5.add(jPanel2);
        jPanel2.setBounds(0, 0, 510, 230);

        tabPane.addTab("Data Barang", jPanel5);

        getContentPane().add(tabPane);
        tabPane.setBounds(20, 10, 500, 270);

        setBounds(0, 0, 549, 337);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        isiTableBarang();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        setAwalForm();
    }//GEN-LAST:event_btnBatalActionPerformed
private void setAwalForm() {
        txtIdBarang.setText("");
        txtNmBarang.setText("");
        txtQty.setText("");
        
        
        btnSimpan.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        
        isiTableBarang();
    }
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        dapatData();
        
        dataBarang = new Object []{idBarang, nama, qty};
        
        if(ctrlComp.cekIsiField(dataBarang)){
                       
                if(ctrlAlert.KONFIRMASI(idBarang, "HAPUS")){
                    String SQL = "DELETE FROM barang WHERE id_brg ='"+idBarang+"';";
                    if(ctrlManData.EXECUTE_QUERY(SQL,idBarang,"HAPUS", true)){
                        setAwalForm();
                    }else{
                        setAwalForm();
                    }
                }    
            
        }else{
            ctrlAlert.getDataKosongMessage();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        dapatData();
        
        dataBarang = new Object []{ idBarang, nama, qty};
        
        if(ctrlComp.cekIsiField(dataBarang)){
       
                if(ctrlAlert.KONFIRMASI(idBarang, "UBAH")){
                    String SQL = "UPDATE barang SET nama_brg='"+nama+"', qty='"+qty+"' WHERE id_brg='"+idBarang+"';";
                    if(ctrlManData.EXECUTE_QUERY(SQL,idBarang,"UBAH", true)){
                        setAwalForm();
                    }else{
                        setAwalForm();
                    }
                }    
            
        }else{
            ctrlAlert.getDataKosongMessage();
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        dapatData();
        
        dataBarang = new Object []{ idBarang, nama, qty};
        
        if(ctrlComp.cekIsiField(dataBarang)){
            
                if(ctrlAlert.KONFIRMASI(idBarang, "SIMPAN")){
                    String SQL = "INSERT INTO barang VALUES('"+idBarang+"','"+nama+"','"+qty+"');";
                    if(ctrlManData.EXECUTE_QUERY(SQL,idBarang,"SIMPAN", true)){
                        setAwalForm();
                    }else{
                        setAwalForm();
                    }
                }    
            
        }else{
            ctrlAlert.getDataKosongMessage();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
     
    int row = 0;
    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        row = tblBarang.getSelectedRow();
        if(evt.getClickCount()==2){
            txtIdBarang.setText(tblBarang.getValueAt(row,0).toString());
            txtNmBarang.setText(tblBarang.getValueAt(row,1).toString());
            txtQty.setText(tblBarang.getValueAt(row,2).toString());
                       
            btnSimpan.setEnabled(false);
            btnUbah.setEnabled(true);
            btnHapus.setEnabled(true);
            
            tabPane.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tblBarangMouseClicked

    private void cbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCariActionPerformed
    
    
    private void isiTableBarang() {  
        dapatData();
        ctrlComp.removeTable(tblBarang,tblModBarang);
        String SQL = "SELECT * FROM barang WHERE "+cariBy+" LIKE '%"+kriteria+"%';";
        ctrlManData.setDefaultTable(SQL,tblModBarang,3);
    }

    private void isiComboCari(){
        cbCari.addItem("ID Barang");
        cbCari.addItem("Nama Barang");        
        cbCari.addItem("Quantity");
        
    }
    
    private void dapatData(){
         switch(cbCari.getSelectedIndex()){
            case 0 : cariBy = "id_brg"; break;
            case 1 : cariBy = "nama_brg"; break;    
            case 2 : cariBy = "qty"; break;
            default : cariBy = "id_brg";
        }
        kriteria = txtCari.getText().trim();
        
        idBarang=txtIdBarang.getText().trim();
        nama=txtNmBarang.getText().trim().replaceAll("'","''");
        qty = ctrlComp.setNoHP(txtQty.getText().trim());
        
        
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox cbCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblIdBarang;
    private javax.swing.JLabel lblNmBarang;
    private javax.swing.JLabel lblQty;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtNmBarang;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
    private String idBarang="", nama="", qty="";    
    public javax.swing.table.DefaultTableModel tblModBarang;    
    private String cariBy="", kriteria="";
    private Object dataBarang[];
}
