package form;
import control.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class frmLoginUser extends javax.swing.JInternalFrame {
    MenuUtama mUtama;
    ctrlKoneksiDB koneksi;
    ctrlAlert ctrlAlert;
    ctrlValidasi ctrlValid;
    
    private Connection cn;
    private Statement st1, st2;
    private String id_admin="",username="", user="", pass="";
    
    /** Creates new form frmLoginUser */
    public frmLoginUser(MenuUtama mUtama) {
        initComponents();
        
        this.mUtama = mUtama;
        koneksi = new ctrlKoneksiDB ();    
        ctrlAlert = new ctrlAlert(mUtama);
        ctrlValid = new ctrlValidasi(mUtama);
        txtUser.requestFocus();
        txtUser.setDocument(new control.ctrlTextDoc(30));
        txtPass.setDocument(new control.ctrlTextDoc(30));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setTitle(":: Form Login  ::");
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        lblUser.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("USERNAME :");
        jPanel1.add(lblUser);
        lblUser.setBounds(10, 30, 120, 25);

        lblPass.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblPass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPass.setText("PASSWORD :");
        jPanel1.add(lblPass);
        lblPass.setBounds(10, 70, 120, 25);

        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });
        jPanel1.add(txtUser);
        txtUser.setBounds(140, 30, 200, 25);

        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        jPanel1.add(txtPass);
        txtPass.setBounds(140, 70, 200, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 90, 380, 120);

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(".::: LOGIN :::.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 80);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setLayout(null);

        btnLogin.setText("MASUK");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin);
        btnLogin.setBounds(90, 10, 90, 30);

        btnCancel.setText("KELUAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);
        btnCancel.setBounds(190, 10, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 220, 380, 50);

        setBounds(0, 0, 410, 318);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        cekLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(true);
        dispose();
        mUtama.setMenu(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cekLogin();
        }
    }//GEN-LAST:event_txtPassKeyPressed

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            cekLogin();
        }
    }//GEN-LAST:event_txtUserKeyPressed
    
    public void cekLogin(){
        user = txtUser.getText().trim();
        pass = String.valueOf(txtPass.getPassword());
        
        if(user.equals("")||pass.equals("")){
            JOptionPane.showMessageDialog(null,"Isi Username Dan Password!","WARNING",2);            
        }
        else if(ctrlValid.cekAdmin(user,pass)){        
            String nama = ctrlValid.getNamaAdmin();
            JOptionPane.showMessageDialog(null,"Halo : "+nama);
//            mUtama.setUsername(nama);
            mUtama.setMenu(true);
            setVisible(false);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Username Dan Password Salah!","WARNING",2);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
    
}
