package form;
import control.*;
import javax.swing.table.DefaultTableModel;


public class frmOutbox extends javax.swing.JInternalFrame {
    MenuUtama mUtama;
    ctrlManipulasiData ctrlManData;
    ctrlComponent ctrlComp; 
    
    /** Creates new form frmInbox */
    public frmOutbox(MenuUtama mUtama) {
        initComponents();
        
        this.mUtama = mUtama;
        ctrlManData = new ctrlManipulasiData(mUtama);
        ctrlComp = new ctrlComponent();
        tblModel = (DefaultTableModel) ctrlComp.getDefaultTabelModel(new String[]{
            "NO.OUTBOX","TANGGAL","WAKTU","ISI SMS","NO.HANDPHONE"
        });        
        
        tblModel1 = (DefaultTableModel) ctrlComp.getDefaultTabelModel(new String[]{
            "NO.BORADCAST","ISI BROADCAST","TANGGAL","WAKTU","ID KARYAWAN"
        });
        tblOutbox.setModel(tblModel);
        ctrlComp.setTabel(tblOutbox, new int[]{100,150,150,320,130});
        isiComboCariOutbox();
        isiTableOutbox();
        
        
        tblBroadcast.setModel(tblModel1);
        ctrlComp.setTabel(tblBroadcast, new int[]{100,150,150,320,130});
        isiComboCariBroadcast();
        isiTableBroadcast();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOutbox = new javax.swing.JTable();
        lblCari1 = new javax.swing.JLabel();
        cmbCariOutbox = new javax.swing.JComboBox();
        txtCarioutbox = new javax.swing.JTextField();
        btnCari1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBroadcast = new javax.swing.JTable();
        lblCari = new javax.swing.JLabel();
        cmbBroadcast = new javax.swing.JComboBox();
        txtCaribroadcast = new javax.swing.JTextField();
        cmbCariBroadcast = new javax.swing.JButton();

        setClosable(true);
        setTitle(":: Form Outbox SMS ::");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM OUTBOX SMS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 60);

        jPanel3.setLayout(null);

        tblOutbox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane3.setViewportView(tblOutbox);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 670, 370);

        lblCari1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCari1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCari1.setText("Cari Berdasarkan :"); // NOI18N
        jPanel3.add(lblCari1);
        lblCari1.setBounds(0, 400, 120, 20);

        jPanel3.add(cmbCariOutbox);
        cmbCariOutbox.setBounds(120, 400, 120, 20);
        jPanel3.add(txtCarioutbox);
        txtCarioutbox.setBounds(240, 400, 130, 20);

        btnCari1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCari1.setText("Cari"); // NOI18N
        btnCari1.setIconTextGap(10);
        btnCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCari1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnCari1);
        btnCari1.setBounds(370, 400, 70, 20);

        tabPane.addTab("Data Outbox", jPanel3);

        jPanel5.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(null);

        tblBroadcast.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tblBroadcast);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 670, 370);

        lblCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCari.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCari.setText("Cari Berdasarkan :"); // NOI18N
        jPanel2.add(lblCari);
        lblCari.setBounds(0, 400, 120, 20);

        jPanel2.add(cmbBroadcast);
        cmbBroadcast.setBounds(120, 400, 110, 20);
        jPanel2.add(txtCaribroadcast);
        txtCaribroadcast.setBounds(230, 400, 130, 20);

        cmbCariBroadcast.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbCariBroadcast.setText("Cari"); // NOI18N
        cmbCariBroadcast.setIconTextGap(10);
        cmbCariBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCariBroadcastActionPerformed(evt);
            }
        });
        jPanel2.add(cmbCariBroadcast);
        cmbCariBroadcast.setBounds(360, 400, 70, 20);

        jPanel5.add(jPanel2);
        jPanel2.setBounds(0, 0, 690, 430);

        tabPane.addTab("Data Broadcast", jPanel5);

        getContentPane().add(tabPane);
        tabPane.setBounds(30, 60, 700, 470);

        setBounds(0, 0, 756, 585);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCari1ActionPerformed
       isiTableOutbox();
    }//GEN-LAST:event_btnCari1ActionPerformed

    private void cmbCariBroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCariBroadcastActionPerformed
        isiTableBroadcast();
    }//GEN-LAST:event_cmbCariBroadcastActionPerformed

    private void isiComboCariOutbox(){
        cmbCariOutbox.addItem("NO. OUTBOX");
        cmbCariOutbox.addItem("TANGGAL");
        cmbCariOutbox.addItem("WAKTU");
        cmbCariOutbox.addItem("ISI");
        cmbCariOutbox.addItem("NO.HANDPHONE");
    }
    
    private void isiComboCariBroadcast(){
        cmbBroadcast.addItem("NO.BROADCAST");
        cmbBroadcast.addItem("TANGGAL");
        cmbBroadcast.addItem("WAKTU");
        cmbBroadcast.addItem("ISI SMS"); 
        cmbBroadcast.addItem("ID.KARYAWAN");
    }
         
    private void isiTableOutbox() {  
        dapatData();
        ctrlComp.removeTable(tblOutbox,tblModel);
        String SQL="SELECT * FROM balas_req WHERE "+cariBy+" LIKE '%"+kriteria+"%' AND "
                + "(SUBSTRING(no_balas_req,1,1)='O') "
                + "ORDER by no_balas_req DESC ";
        System.out.println("SQL="+SQL);
        ctrlManData.setDefaultTable(SQL,tblModel,5);
   }
    
    private void isiTableBroadcast() {  
        dapatData2();
        ctrlComp.removeTable(tblBroadcast,tblModel1);
        String SQL2="SELECT * FROM broadcast WHERE "+cariBy+" LIKE '%"+kriteria+"%' AND "
                + "(SUBSTRING(no_broadcast,1,1)='B') "
                + "ORDER by no_broadcast DESC ";
        ctrlManData.setDefaultTable(SQL2,tblModel1,5);
   }
    
    private void dapatData(){
         switch(cmbCariOutbox.getSelectedIndex()){
            case 0 : cariBy = "no_balas_req"; break;
            case 1 : cariBy = "tgl_sms"; break;
            case 2 : cariBy = "waktu_Sms"; break;
            case 3 : cariBy = "isi_sms"; break;
            case 4 : cariBy = "no_sms_req"; break;
            default : cariBy = "no_balas_req";
        }
         
        kriteria = txtCarioutbox.getText().trim();     
    }
    
    private void dapatData2(){
         switch(cmbBroadcast.getSelectedIndex()){
            case 0 : cariBy = "no_broadcast"; break;
            case 1 : cariBy = "tgl_sms"; break;
            case 2 : cariBy = "waktu_Sms"; break;
            case 3 : cariBy = "isi_sms"; break;
            case 4 : cariBy = "id_karyawan"; break;
            default : cariBy = "no_broadcast";
        }
         
        kriteria = txtCaribroadcast.getText().trim();     
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari1;
    private javax.swing.JComboBox cmbBroadcast;
    private javax.swing.JButton cmbCariBroadcast;
    private javax.swing.JComboBox cmbCariOutbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblCari1;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tblBroadcast;
    private javax.swing.JTable tblOutbox;
    private javax.swing.JTextField txtCaribroadcast;
    private javax.swing.JTextField txtCarioutbox;
    // End of variables declaration//GEN-END:variables
    public javax.swing.table.DefaultTableModel tblModel; 
    public javax.swing.table.DefaultTableModel tblModel1; 
    private String cariBy="", kriteria="";
}
