package form;

import control.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class frmPO extends javax.swing.JInternalFrame {
    MenuUtama mUtama;
    ctrlManipulasiData ctrlManData;
    ctrlAlert ctrlAlert;    
    ctrlComponent ctrlComp;    
    ctrlKoneksiDB koneksi;
    
    public frmPO(MenuUtama mUtama) {
        initComponents();
        this.mUtama = mUtama;
        ctrlManData = new ctrlManipulasiData(mUtama);
        ctrlAlert = new ctrlAlert(mUtama);        
        ctrlComp = new ctrlComponent();
        koneksi = new ctrlKoneksiDB();
        tblModel = (DefaultTableModel) ctrlComp.getDefaultTabelModel(new String[]{
            "Nomor PO","Tanggal PO","Tanggal Masuk","ID Barang","Nama Barang","Quantity","Harga"
        });
        tblPO.setModel(tblModel);
        ctrlComp.setTabel(tblPO, new int[]{100,120,200,100,100,100,100,100});        
        txtNoPO.setDocument(new control.ctrlTextDoc(10));
        jdTglPO.setDate(new Date());
        jdTglMasuk.setDate(new Date());
        txtIdBarang.setDocument(new control.ctrlTextDoc(5));
        txtNmBarang.setDocument(new control.ctrlTextDoc(30)); 
        txtQty.setDocument(new control.ctrlTextDoc(11, control.ctrlTextDoc.DESIMAL));
        txtIdSupplier.setDocument(new control.ctrlTextDoc(5));
        txtNmSupplier.setDocument(new control.ctrlTextDoc(30));
        txtHarga.setDocument(new control.ctrlTextDoc(11, control.ctrlTextDoc.DESIMAL));
        
        isiComboCari();
        setAwalForm();    
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanePO = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblNoPO = new javax.swing.JLabel();
        txtNoPO = new javax.swing.JTextField();
        lblTglPO = new javax.swing.JLabel();
        jdTglPO = new com.toedter.calendar.JDateChooser();
        lblTglMasuk = new javax.swing.JLabel();
        jdTglMasuk = new com.toedter.calendar.JDateChooser();
        lblIdBarang = new javax.swing.JLabel();
        lblNmBarang = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        lblQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        lblHarga = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtNmBarang = new javax.swing.JTextField();
        lblIdSupplier = new javax.swing.JLabel();
        lblNmSupplier = new javax.swing.JLabel();
        txtNmSupplier = new javax.swing.JTextField();
        txtIdSupplier = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPO = new javax.swing.JTable();
        lblCari = new javax.swing.JLabel();
        cmbCari = new javax.swing.JComboBox();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setClosable(true);
        setTitle("::FORM TRANSAKSI ::"); // NOI18N
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Isi Data Dengan Lengkap"));
        jPanel4.setLayout(null);

        jPanel1.setLayout(null);

        lblNoPO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNoPO.setText("Nomor PO : ");
        jPanel1.add(lblNoPO);
        lblNoPO.setBounds(10, 10, 110, 25);

        txtNoPO.setEditable(false);
        txtNoPO.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNoPOCaretUpdate(evt);
            }
        });
        txtNoPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoPOActionPerformed(evt);
            }
        });
        txtNoPO.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtNoPOPropertyChange(evt);
            }
        });
        txtNoPO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoPOKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoPOKeyTyped(evt);
            }
        });
        jPanel1.add(txtNoPO);
        txtNoPO.setBounds(130, 10, 100, 25);

        lblTglPO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTglPO.setText("Tanggal PO : ");
        jPanel1.add(lblTglPO);
        lblTglPO.setBounds(20, 50, 100, 20);
        jPanel1.add(jdTglPO);
        jdTglPO.setBounds(130, 50, 130, 20);

        lblTglMasuk.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTglMasuk.setText("Tanggal Masuk : ");
        jPanel1.add(lblTglMasuk);
        lblTglMasuk.setBounds(20, 80, 100, 20);
        jPanel1.add(jdTglMasuk);
        jdTglMasuk.setBounds(130, 80, 130, 20);

        lblIdBarang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdBarang.setText("ID Barang :");
        jPanel1.add(lblIdBarang);
        lblIdBarang.setBounds(10, 110, 110, 25);

        lblNmBarang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNmBarang.setText("Nama Barang : ");
        jPanel1.add(lblNmBarang);
        lblNmBarang.setBounds(10, 150, 110, 25);

        txtIdBarang.setEditable(false);
        jPanel1.add(txtIdBarang);
        txtIdBarang.setBounds(130, 110, 100, 25);

        lblQty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQty.setText("Quantity : ");
        jPanel1.add(lblQty);
        lblQty.setBounds(10, 190, 110, 25);
        jPanel1.add(txtQty);
        txtQty.setBounds(130, 190, 110, 25);

        lblHarga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHarga.setText("Harga :");
        jPanel1.add(lblHarga);
        lblHarga.setBounds(10, 310, 110, 25);

        txtHarga.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtHargaCaretUpdate(evt);
            }
        });
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        txtHarga.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtHargaPropertyChange(evt);
            }
        });
        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHargaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaKeyTyped(evt);
            }
        });
        jPanel1.add(txtHarga);
        txtHarga.setBounds(130, 310, 110, 25);

        txtNmBarang.setEditable(false);
        jPanel1.add(txtNmBarang);
        txtNmBarang.setBounds(130, 150, 170, 25);

        lblIdSupplier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdSupplier.setText("ID Supplier :");
        jPanel1.add(lblIdSupplier);
        lblIdSupplier.setBounds(10, 230, 110, 25);

        lblNmSupplier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNmSupplier.setText("Nama Supplier :");
        jPanel1.add(lblNmSupplier);
        lblNmSupplier.setBounds(10, 270, 110, 25);

        txtNmSupplier.setEditable(false);
        jPanel1.add(txtNmSupplier);
        txtNmSupplier.setBounds(130, 270, 100, 25);

        txtIdSupplier.setEditable(false);
        jPanel1.add(txtIdSupplier);
        txtIdSupplier.setBounds(130, 230, 100, 25);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/browse.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(240, 230, 40, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/browse.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(240, 110, 40, 30);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(10, 20, 460, 360);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(20, 0, 480, 400);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save.png"))); // NOI18N
        btnSimpan.setIconTextGap(10);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan);
        btnSimpan.setBounds(50, 410, 80, 40);

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        btnUbah.setIconTextGap(10);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel3.add(btnUbah);
        btnUbah.setBounds(160, 410, 80, 40);

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        btnBatal.setIconTextGap(10);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel3.add(btnBatal);
        btnBatal.setBounds(270, 410, 80, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(380, 410, 80, 40);

        tabPanePO.addTab("Form Input Data PO", jPanel3);

        jPanel5.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(null);

        tblPO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPOMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPO);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 490, 390);

        lblCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCari.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCari.setText("Cari Berdasarkan :"); // NOI18N
        jPanel2.add(lblCari);
        lblCari.setBounds(0, 420, 120, 20);

        cmbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCariActionPerformed(evt);
            }
        });
        jPanel2.add(cmbCari);
        cmbCari.setBounds(120, 420, 80, 20);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        jPanel2.add(txtCari);
        txtCari.setBounds(200, 420, 130, 20);

        btnCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCari.setText("Cari"); // NOI18N
        btnCari.setIconTextGap(10);
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel2.add(btnCari);
        btnCari.setBounds(330, 420, 70, 20);

        jPanel5.add(jPanel2);
        jPanel2.setBounds(0, 0, 510, 450);

        tabPanePO.addTab("Data PO", jPanel5);

        getContentPane().add(tabPanePO);
        tabPanePO.setBounds(10, 10, 520, 490);

        getAccessibleContext().setAccessibleName("::FORM TRANSAKSI ::");

        setBounds(0, 0, 549, 542);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
     CariIsiTablePO();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        setAwalForm();
    }//GEN-LAST:event_btnBatalActionPerformed
private void setAwalForm() {
        txtNoPO.setText(""+new ctrlIDgenerator().getIDPO());
        jdTglPO.setDate(new Date());
        jdTglMasuk.setDate(new Date());
        txtIdBarang.setText("");        
        txtNmBarang.setText("");
        txtQty.setText("");
        txtHarga.setText("");
        txtIdSupplier.setText("");
        txtNmSupplier.setText("");
        
        btnSimpan.setEnabled(true);
        btnUbah.setEnabled(false);
        isiTablePO();
    }
     
    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
          dapatData();
        dataPO = new Object []{noPO, tglPO, tglMasuk, idBarang, nmBarang,qty,idSupplier, harga};
        if(ctrlComp.cekIsiField(dataPO)){
            if(ctrlAlert.KONFIRMASI(noPO,"UBAH")){
              String SQL = "UPDATE po SET tgl_po='"+tglPO+"', tgl_masuk='"+tglMasuk+"'," +
                           "nama_brg='"+nmBarang+"', qty='"+qty+"', id_supplier='"+idSupplier+"' WHERE no_po='"+noPO+"';";
                           ctrlManData.EXECUTE_QUERY_TABLE(SQL);
              String SQL2 = "UPDATE det_po SET id_brg='"+idBarang+"', harga ='"+harga+"' " +
                            "WHERE no_po='"+noPO+"';";
                               ctrlManData.EXECUTE_QUERY_TABLE(SQL2);
                               isiTablePO();
                }else{
                    setAwalForm();
                }
          
        }else{
            ctrlAlert.getDataKosongMessage();
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       dapatData();
        dataPO = new Object []{noPO, tglPO, tglMasuk, idBarang, nmBarang,qty,idSupplier, harga};
        if(ctrlComp.cekIsiField(dataPO)){
            if(ctrlAlert.KONFIRMASI(noPO, "SIMPAN")){
                String SQL2 = "INSERT INTO po VALUES('"+noPO+"','"+tglPO+"','"+tglMasuk+"','"+nmBarang+"','"+qty+"','"+idSupplier+"');";          
                ctrlManData.EXECUTE_QUERY_TABLE(SQL2);
                String SQL = "INSERT INTO det_po VALUES('"+noPO+"','"+idBarang+"','"+harga+"');";
                ctrlManData.EXECUTE_QUERY_TABLE(SQL);
                isiTablePO();                   
                }else{
                        setAwalForm();
                    }
            
        }else{
            ctrlAlert.getDataKosongMessage();
        }
              
    }//GEN-LAST:event_btnSimpanActionPerformed
 
    private void tblPOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPOMouseClicked
        row = tblPO.getSelectedRow();
        if(evt.getClickCount() == 2){
            txtNoPO.setText(tblPO.getValueAt(row, 0).toString());
            jdTglPO.setDate(getTanggalPO(tblPO.getValueAt(row, 0).toString()));
            jdTglMasuk.setDate(getTanggalMasuk(tblPO.getValueAt(row, 0).toString()));
            txtIdBarang.setText(tblPO.getValueAt(row, 3).toString());
            txtNmBarang.setText(cariNamaBarang(tblPO.getValueAt(row, 3).toString()));                     
            txtQty.setText(cariQty(tblPO.getValueAt(row, 3).toString()));
            txtHarga.setText(tblPO.getValueAt(row, 4).toString());
            
            btnSimpan.setEnabled(false);
            btnUbah.setEnabled(true);
            tabPanePO.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tblPOMouseClicked

    private void cmbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCariActionPerformed

    private void txtNoPOCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNoPOCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPOCaretUpdate

    private void txtNoPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPOActionPerformed

    private void txtNoPOPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtNoPOPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPOPropertyChange

    private void txtNoPOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoPOKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPOKeyPressed

    private void txtNoPOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoPOKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPOKeyTyped

    private void txtHargaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtHargaCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaCaretUpdate

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtHargaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtHargaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaPropertyChange

    private void txtHargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaKeyPressed

    private void txtHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                final popUpSupplier dialog = new popUpSupplier (new javax.swing.JFrame(), true, mUtama);
                Dimension scrSize = Toolkit.getDefaultToolkit().getScreenSize(),
                          frmSize = dialog.getSize();
                dialog.setLocation((scrSize.width - frmSize.width)/2,(scrSize.height - (frmSize.height + 100))/2);

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.dispose();
                    }
                });
                dialog.setVisible(true);
                txtIdSupplier.setText(dialog.getIdSupplier());
                txtNmSupplier.setText(dialog.getNamaSupplier());
            }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                final popUpBarang dialog = new popUpBarang (new javax.swing.JFrame(), true, mUtama);
                Dimension scrSize = Toolkit.getDefaultToolkit().getScreenSize(),
                          frmSize = dialog.getSize();
                dialog.setLocation((scrSize.width - frmSize.width)/2,(scrSize.height - (frmSize.height + 100))/2);

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.dispose();
                    }
                });
                dialog.setVisible(true);
                txtIdBarang.setText(dialog.getIdBarang());
                txtNmBarang.setText(dialog.getNamaBarang());
                
            }
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
   
    }//GEN-LAST:event_txtCariKeyReleased
  

int row = 0;

    private String cariNamaBarang(String NamaBarang){
        String query = "select nama_brg from po where no_po = '"+NamaBarang+"'";
        return ctrlManipulasiData.EXECUTE_QUERY(query);     
    }
    
    private String cariQty(String Qty){
        String query = "select qty from po where no_po = '"+Qty+"'";
        return ctrlManipulasiData.EXECUTE_QUERY(query);
     
    }  
       
    private Date getTanggalPO(String tglPO){
        String SQL = "SELECT tgl_po FROM po where no_po = '"+tglPO+"'";
        return ctrlManData.getTanggal(SQL);
    }

    private Date getTanggalMasuk(String tglMsk ){
        String SQL = "SELECT tgl_masuk FROM po where no_po = '"+tglMsk+"'";
        return ctrlManData.getTanggal(SQL);
    }

    private void isiTablePO() {  
        dapatData();
        ctrlComp.removeTable(tblPO,tblModel);
        String SQL = "SELECT p.no_po, p.tgl_po, p.tgl_masuk, d.id_brg, p.nama_brg, p.qty, d.harga "+
                     "FROM po p, det_po d "+
                     "WHERE p.no_po = d.no_po";
                     ctrlManData.setDefaultTable(SQL,tblModel,7);                     
        
    }               
     private void CariIsiTablePO() {  
        dapatData();
        ctrlComp.removeTable(tblPO,tblModel);
        String SQL = "SELECT p.no_po, p.tgl_po, p.tgl_masuk, d.id_brg, p.nama_brg, p.qty, d.harga "+
                     "FROM po p, det_po d "+
                     "WHERE p.no_po = d.no_po AND "+cariBy+" LIKE '%"+kriteria+"%' ORDER BY p.no_po DESC ";    
                     ctrlManData.setDefaultTable(SQL,tblModel,7);                     
        
    } 
    private void removeTable(JTable tabel, DefaultTableModel Model){
        for(int i=tabel.getRowCount(); i>0; i--) {
            Model.removeRow(i-1);
        }
    }
    
    
     private void isiComboCari(){
        cmbCari.addItem("NO PO");
        cmbCari.addItem("TANGGAL PO");
        cmbCari.addItem("TANGGAL MASUK");
        cmbCari.addItem("ID BARANG");
        cmbCari.addItem("NAMA BARANG");
        cmbCari.addItem("QUANTITY");
        cmbCari.addItem("HARGA");
        
    }
    
    private void dapatData(){
         switch(cmbCari.getSelectedIndex()){
            case 0 : cariBy = "p.no_po"; break;
            case 1 : cariBy = "tgl_po"; break;
            case 2 : cariBy = "tgl_masuk"; break;
            case 3 : cariBy = "id_brg"; break;
            case 4 : cariBy = "nama_brg"; break;
            case 5 : cariBy = "qty"; break;
            case 6 : cariBy = "harga"; break;
            default : cariBy = "p.no_po";
        }
         
        kriteria = txtCari.getText().trim();
          
        noPO  = txtNoPO.getText().trim();
        tglPO = new java.text.SimpleDateFormat("yyyy-MM-dd").format(jdTglPO.getDate());
        tglMasuk= new java.text.SimpleDateFormat("yyyy-MM-dd").format(jdTglMasuk.getDate());
        idBarang  = txtIdBarang.getText().trim();
        nmBarang  = txtNmBarang.getText().trim();
        qty  = txtQty.getText().trim();
        harga  = txtHarga.getText().trim(); 
        idSupplier  = txtIdSupplier.getText().trim(); 
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox cmbCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdTglMasuk;
    private com.toedter.calendar.JDateChooser jdTglPO;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblIdBarang;
    private javax.swing.JLabel lblIdSupplier;
    private javax.swing.JLabel lblNmBarang;
    private javax.swing.JLabel lblNmSupplier;
    private javax.swing.JLabel lblNoPO;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblTglMasuk;
    private javax.swing.JLabel lblTglPO;
    private javax.swing.JTabbedPane tabPanePO;
    private javax.swing.JTable tblPO;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtIdSupplier;
    private javax.swing.JTextField txtNmBarang;
    private javax.swing.JTextField txtNmSupplier;
    private javax.swing.JTextField txtNoPO;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
    private String noPO="", tglMasuk="", tglPO="", idBarang="", nmBarang="",  qty="",  harga="",idSupplier="",nmSupplier="";
    public javax.swing.table.DefaultTableModel tblModel;    
    private String cariBy="", kriteria="";
    private Object dataPO[];
}
