package form;

import control.*;
import javax.swing.table.DefaultTableModel;


public class frmSupplier extends javax.swing.JInternalFrame {
    MenuUtama mUtama;
    ctrlManipulasiData ctrlManData;
    ctrlAlert ctrlAlert;    
    ctrlComponent ctrlComp;    
    ctrlValidasi ctrlValid;
    

    public frmSupplier(MenuUtama mUtama) {
        initComponents();
        this.mUtama = mUtama;
        ctrlManData = new ctrlManipulasiData(mUtama);
        ctrlAlert = new ctrlAlert(mUtama);        
        ctrlComp = new ctrlComponent();
        ctrlValid = new ctrlValidasi(mUtama);
        
        tblModSupplier = (DefaultTableModel) ctrlComp.getDefaultTabelModel(new String[]{
           "ID Supplier ", "Nama Supplier", "Alamat","Nomer HP"
        });
        tblSupplier.setModel(tblModSupplier);
        ctrlComp.setTabel(tblSupplier, new int[]{100,125,200,100,130,200});
        
        txtIdSupplier.setDocument(new control.ctrlTextDoc(5));
        txtNmSupplier.setDocument(new control.ctrlTextDoc(40));
        txtAlamat.setDocument(new control.ctrlTextDoc(125)); 
        txtNoHp.setDocument(new control.ctrlTextDoc(15, control.ctrlTextDoc.DESIMAL));
        
        
        setAwalForm();
        isiComboCari();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblNmSupplier = new javax.swing.JLabel();
        txtNmSupplier = new javax.swing.JTextField();
        lblAlamat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        lblIdSupplier = new javax.swing.JLabel();
        txtIdSupplier = new javax.swing.JTextField();
        lblNoHp = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        lblCari = new javax.swing.JLabel();
        cbCari = new javax.swing.JComboBox();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setClosable(true);
        setTitle("::FORM MASTER SUPPLIER ::"); // NOI18N
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Isi Data Dengan Lengkap"));
        jPanel4.setLayout(null);

        jPanel1.setLayout(null);

        lblNmSupplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNmSupplier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNmSupplier.setText("Nama Supplier :"); // NOI18N
        jPanel1.add(lblNmSupplier);
        lblNmSupplier.setBounds(20, 50, 130, 25);

        txtNmSupplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtNmSupplier);
        txtNmSupplier.setBounds(160, 50, 250, 25);

        lblAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAlamat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAlamat.setText("Alamat :"); // NOI18N
        jPanel1.add(lblAlamat);
        lblAlamat.setBounds(10, 100, 140, 50);

        txtAlamat.setColumns(20);
        txtAlamat.setLineWrap(true);
        txtAlamat.setRows(3);
        txtAlamat.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(160, 90, 250, 80);

        lblIdSupplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIdSupplier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdSupplier.setText("ID Supplier :"); // NOI18N
        jPanel1.add(lblIdSupplier);
        lblIdSupplier.setBounds(20, 10, 130, 25);

        txtIdSupplier.setEditable(false);
        txtIdSupplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtIdSupplier);
        txtIdSupplier.setBounds(160, 10, 250, 25);

        lblNoHp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNoHp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNoHp.setText("No. Handphone :"); // NOI18N
        jPanel1.add(lblNoHp);
        lblNoHp.setBounds(10, 190, 140, 25);

        txtNoHp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtNoHp);
        txtNoHp.setBounds(160, 190, 250, 25);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(10, 20, 460, 230);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(20, 0, 480, 260);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save.png"))); // NOI18N
        btnSimpan.setIconTextGap(10);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan);
        btnSimpan.setBounds(40, 270, 80, 40);

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        btnUbah.setIconTextGap(10);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel3.add(btnUbah);
        btnUbah.setBounds(130, 270, 80, 40);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnHapus);
        btnHapus.setBounds(220, 270, 80, 40);

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        btnBatal.setIconTextGap(10);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel3.add(btnBatal);
        btnBatal.setBounds(310, 270, 80, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(400, 270, 80, 40);

        tabPane.addTab("Form Input Data Supplier", jPanel3);

        jPanel5.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(null);

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 520, 260);

        lblCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCari.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCari.setText("Cari Berdasarkan :"); // NOI18N
        jPanel2.add(lblCari);
        lblCari.setBounds(10, 280, 120, 20);

        cbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCariActionPerformed(evt);
            }
        });
        jPanel2.add(cbCari);
        cbCari.setBounds(130, 280, 80, 20);
        jPanel2.add(txtCari);
        txtCari.setBounds(210, 280, 130, 20);

        btnCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCari.setText("Cari"); // NOI18N
        btnCari.setIconTextGap(10);
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel2.add(btnCari);
        btnCari.setBounds(340, 280, 70, 20);

        jPanel5.add(jPanel2);
        jPanel2.setBounds(10, 10, 540, 310);

        tabPane.addTab("Data Supplier", jPanel5);

        getContentPane().add(tabPane);
        tabPane.setBounds(20, 10, 560, 350);

        setBounds(0, 0, 604, 408);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        isiTableSupplier();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        setAwalForm();
    }//GEN-LAST:event_btnBatalActionPerformed
private void setAwalForm() {
        txtIdSupplier.setText(""+new ctrlIDgenerator().getIDSupplier());
        txtNmSupplier.setText("");
        txtAlamat.setText("");
        txtNoHp.setText("");
        
        
        btnSimpan.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        
        isiTableSupplier();
    }
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        dapatData();
        
        dataSupplier = new Object []{idSupplier, nama, noHp, alamat};
        
        if(ctrlComp.cekIsiField(dataSupplier)){
                       
                if(ctrlAlert.KONFIRMASI(idSupplier, "HAPUS")){
                    String SQL = "DELETE FROM supplier WHERE id_supplier ='"+idSupplier+"';";
                    if(ctrlManData.EXECUTE_QUERY(SQL,idSupplier,"HAPUS", true)){
                        setAwalForm();
                    }else{
                        setAwalForm();
                    }
                }    
            
        }else{
            ctrlAlert.getDataKosongMessage();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        dapatData();
        
        dataSupplier = new Object []{ idSupplier, nama,noHp, alamat};
        
        if(ctrlComp.cekIsiField(dataSupplier)){
       
                if(ctrlAlert.KONFIRMASI(idSupplier, "UBAH")){
                    String SQL = "UPDATE supplier SET nama_supplier='"+nama+"', alamat='"+alamat+"', no_hp='"+noHp+"' WHERE id_supplier='"+idSupplier+"';";
                    if(ctrlManData.EXECUTE_QUERY(SQL,idSupplier,"UBAH", true)){
                        setAwalForm();
                    }else{
                        setAwalForm();
                    }
                }    
            
        }else{
            ctrlAlert.getDataKosongMessage();
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        dapatData();
        
        dataSupplier = new Object []{ idSupplier, nama, alamat, noHp};
        
        if(ctrlComp.cekIsiField(dataSupplier)){
            
                if(ctrlAlert.KONFIRMASI(idSupplier, "SIMPAN")){
                    String SQL = "INSERT INTO supplier VALUES('"+idSupplier+"','"+nama+"','"+alamat+"','"+noHp+"');";
                    if(ctrlManData.EXECUTE_QUERY(SQL,idSupplier,"SIMPAN", true)){
                        setAwalForm();
                    }else{
                        setAwalForm();
                    }
                }    
            
        }else{
            ctrlAlert.getDataKosongMessage();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
     
    int row = 0;
    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        row = tblSupplier.getSelectedRow();
        if(evt.getClickCount()==2){
            txtIdSupplier.setText(tblSupplier.getValueAt(row,0).toString());
            txtNmSupplier.setText(tblSupplier.getValueAt(row,1).toString());         
            txtAlamat.setText(tblSupplier.getValueAt(row,2).toString());
            txtNoHp.setText(tblSupplier.getValueAt(row,3).toString());
                       
            btnSimpan.setEnabled(false);
            btnUbah.setEnabled(true);
            btnHapus.setEnabled(true);
            
            tabPane.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void cbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCariActionPerformed
    
    
    private void isiTableSupplier() {  
        dapatData();
        ctrlComp.removeTable(tblSupplier,tblModSupplier);
        String SQL = "SELECT * FROM supplier WHERE "+cariBy+" LIKE '%"+kriteria+"%';";
        ctrlManData.setDefaultTable(SQL,tblModSupplier,4);
    }

    private void isiComboCari(){
        cbCari.addItem("ID Supplier");
        cbCari.addItem("Nama Supplier");        
        cbCari.addItem("Alamat");
        cbCari.addItem("Nomer HP");
        
    }
    
    private void dapatData(){
         switch(cbCari.getSelectedIndex()){
            case 0 : cariBy = "id_supplier"; break;
            case 1 : cariBy = "nama_supplier"; break;    
            case 2 : cariBy = "alamat"; break;
            case 3 : cariBy = "no_hp"; break;
            default : cariBy = "id_supplier";
        }
        kriteria = txtCari.getText().trim();
        
        idSupplier=txtIdSupplier.getText().trim();
        nama=txtNmSupplier.getText().trim().replaceAll("'","''");        
        alamat = txtAlamat.getText().trim();
        noHp = ctrlComp.setNoHP(txtNoHp.getText().trim());
        
        
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox cbCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblIdSupplier;
    private javax.swing.JLabel lblNmSupplier;
    private javax.swing.JLabel lblNoHp;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdSupplier;
    private javax.swing.JTextField txtNmSupplier;
    private javax.swing.JTextField txtNoHp;
    // End of variables declaration//GEN-END:variables
    private String idSupplier="", nama="", alamat="", noHp="";    
    public javax.swing.table.DefaultTableModel tblModSupplier;    
    private String cariBy="", kriteria="";
    private Object dataSupplier[];
}
